name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
        
        # run build and test           
      - name: Restore dependencies
        run: dotnet restore ManagedCode.Orleans.Identity.sln

      - name: Build
        run: dotnet build ManagedCode.Orleans.Identity.sln --configuration Release --no-restore

      - name: Analyze
        run: dotnet build ManagedCode.Orleans.Identity.sln --configuration Release --no-restore -p:RunAnalyzers=true

      - name: Test and Collect Code Coverage
        run: dotnet test ManagedCode.Orleans.Identity.sln --configuration Release --no-build --verbosity normal -p:CollectCoverage=true -p:CoverletOutput=coverage/ -p:CoverletOutputFormat=opencover

      - name: Copy coverage files
        run: |
          mkdir '${{ github.workspace }}/coverage'
          find . -name "*.opencover.xml" -exec sh -c 'cp "$0" "coverage/coverage-$(basename $0)"' {} \;

      - name: List coverage files
        run: ls '${{ github.workspace }}/coverage/'


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/*.opencover.xml
          fail_ci_if_error: false

#      - name: coveralls
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{secrets.GITHUB_TOKEN }}
#          path-to-lcov: coverage/coverage.info
